version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: admin
      POSTGRES_DB: keycloak
    networks:
      - local
    ports:
      - "5432:5432"


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./cert:/certificates
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    command:
      - start
      - --features=token-exchange
      - --https-certificate-file=/certificates/keycloak.crt
      - --https-certificate-key-file=/certificates/keycloak.pem
      - --hostname=yourip
      - --proxy=edge
      - --db=postgres
      - --db-url-host=postgres
      - --db-url-port=5432
      - --db-url-database=keycloak
      - --db-username=admin
      - --db-password=password
    depends_on:
      - "postgres"
    networks:
      - local

networks:
  local:

volumes:
  postgres_data:
